POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplcmlrMiIsImlkIjoiNjNiMWI0MzllYzdmZDI1NmVlYjM0NTNjIiwiaWF0IjoxNjcyNjc4NjIyfQ.rBBf7Yozq_dCysEXSXA2MGNoEKOII_I_MY1G-cR4Bl8

{
    "url": "www.testblog.blog/notarealone",
    "title": "Test blog",
    "author": "Jani",
    "userId": "63a09ccfeebf92af09f6325f",
    "likes": 42
}